###

GET http://localhost:3000


###

GET http://localhost:3000/productos


###

POST http://localhost:3000/productos
Content-Type: application/json

{
     "id":3,
     
    "nombre" : "gorra",
    "precio" :20

}
